background_path = "/home/synthyaga/.bd/stock-reparadores/images/background.png"
data_path = "/home/synthyaga/.bd/stock-reparadores/.cache/temp.toml"

[table_names]
Capacitor = "capacitors"
"Circuito Integrado" = "integrated_circuits"
"Mem√≥ria" = "memories"
Driver = "drivers"
Transistor = "transistors"
